#Makefile for UVM Testbench - Lab 10

# SIMULATOR = Questa for Mentor's Questasim
# SIMULATOR = VCS for Synopsys's VCS

SIMULATOR =  Questa

FSDB_PATH=/home/cad/eda/SYNOPSYS/VERDI_2022/verdi/T-2022.06-SP1/share/PLI/VCS/LINUX64


RTL= ../rtl/*       +define+WRAPPING_INCR
work= work #library name
SVTB1= ../tb/top.sv
INC = +incdir+../tb +incdir+../test +incdir+../AHB_agent +incdir+../APB_agent
SVTB2 = ../test/test_pkg.sv
VSIMOPT= -vopt -voptargs=+acc 
VSIMCOV= -coverage -sva 


VSIMBATCH_IDLE= -c -do  " log -r /* ;coverage save -onexit mem_cov_idle;run -all; exit"
VSIMBATCH_BUSY= -c -do  " log -r /* ;coverage save -onexit mem_cov_busy;run -all; exit"
VSIMBATCH0= -c -do  " log -r /* ;coverage save -onexit mem_cov0;run -all; exit"
VSIMBATCH1= -c -do  " log -r /* ;coverage save -onexit mem_cov1;run -all; exit"
VSIMBATCH2= -c -do  " log -r /* ;coverage save -onexit mem_cov2;run -all; exit"
VSIMBATCH3= -c -do  " log -r /* ;coverage save -onexit mem_cov3;run -all; exit"
VSIMBATCH4= -c -do  " log -r /* ;coverage save -onexit mem_cov4;run -all; exit"
VSIMBATCH5= -c -do  " log -r /* ;coverage save -onexit mem_cov5;run -all; exit"
VSIMBATCH6= -c -do  " log -r /* ;coverage save -onexit mem_cov6;run -all; exit"
VSIMBATCH7= -c -do  " log -r /* ;coverage save -onexit mem_cov7;run -all; exit"



help:
	@echo =============================================================================================================
	@echo "! USAGE   	--  make target                  								!"
	@echo "! clean   	=>  clean the earlier log and intermediate files.  						!"
	@echo "! sv_cmp    	=>  Create library and compile the code.           						!"
	@echo "! run_test	=>  clean, compile & run the simulation for base_test in batch mode.				!" 
	@echo "! run_test1	=>  clean, compile & run the simulation for test1 in batch mode.				!" 
	@echo "! run_test2	=>  clean, compile & run the simulation for test2 in batch mode.				!"
	@echo "! run_test3	=>  clean, compile & run the simulation for test3 in batch mode.				!" 
	@echo "! view_wave1 =>  To view the waveform of test1	    								!" 
	@echo "! view_wave2 =>  To view the waveform of test2	    								!" 
	@echo "! view_wave3 =>  To view the waveform of test3 	  								!" 
	@echo "! view_wave4 =>  To view the waveform of test4    								!" 
	@echo "! regress    =>  clean, compile and run all testcases in batch mode.		    				!"
	@echo "! report     =>  To merge coverage reports for all testcases and  convert to html format.			!"
	@echo "! cov        =>  To open merged coverage report in html format.							!"
	@echo ====================================================================================================================

clean : clean_$(SIMULATOR)
sv_cmp : sv_cmp_$(SIMULATOR)
run_test : run_test_$(SIMULATOR)

run_test_idle : run_test_idle_$(SIMULATOR)
run_test_busy : run_test_busy_$(SIMULATOR)

run_test0 : run_test0_$(SIMULATOR)
run_test1 : run_test1_$(SIMULATOR)
run_test2 : run_test2_$(SIMULATOR)
run_test3 : run_test3_$(SIMULATOR)
run_test4 : run_test4_$(SIMULATOR)
run_test5 : run_test5_$(SIMULATOR)
run_test6 : run_test6_$(SIMULATOR)
run_test7 : run_test7_$(SIMULATOR)


####### VIRTUAL_TESTS   #############
run_vtest0 : run_vtest0_$(SIMULATOR)
run_vtest1 : run_vtest1_$(SIMULATOR)
run_vtest2 : run_vtest2_$(SIMULATOR)
run_vtest3 : run_vtest3_$(SIMULATOR)
run_vtest4 : run_vtest4_$(SIMULATOR)
run_vtest5 : run_vtest5_$(SIMULATOR)
run_vtest6 : run_vtest6_$(SIMULATOR)
run_vtest7 : run_vtest7_$(SIMULATOR)

run_vtest_idle : run_vtest_idle_$(SIMULATOR)
run_vtest_busy : run_vtest_busy_$(SIMULATOR)

vregress : vregress_$(SIMULATOR)

####################################

view_wave0 : view_wave0_$(SIMULATOR)
view_wave1 : view_wave1_$(SIMULATOR)
view_wave2 : view_wave2_$(SIMULATOR)
view_wave3 : view_wave3_$(SIMULATOR)
view_wave4 : view_wave4_$(SIMULATOR)
view_wave5 : view_wave5_$(SIMULATOR)
view_wave6 : view_wave6_$(SIMULATOR)
view_wave7 : view_wave7_$(SIMULATOR)

regress : regress_$(SIMULATOR)
report : report_$(SIMULATOR)
cov : cov_$(SIMULATOR)

# ----------------------------- Start of Definitions for Mentor's Questa Specific Targets -------------------------------#

sv_cmp_Questa:
	vlib $(work)
	vmap work $(work)
	vlog -work $(work) $(RTL) $(INC) $(SVTB2) $(SVTB1) 	
	
run_test_Questa: sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH0)  -wlf wave_file0.wlf -l test0.log  -sv_seed random  work.top +UVM_TESTNAME=base_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov

run_test_idle_Questa: sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH_IDLE)  -wlf wave_file_idle.wlf -l test_idle.log  -sv_seed random  work.top +UVM_TESTNAME=test_idle
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov_idle
	
run_test_busy_Questa: sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH_BUSY)  -wlf wave_file_busy.wlf -l test_busy.log  -sv_seed random  work.top +UVM_TESTNAME=test_busy
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov_busy
	
run_test0_Questa: sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH0)  -wlf wave_file0.wlf -l test0.log  -sv_seed random  work.top +UVM_TESTNAME=test0
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov0
	

run_test1_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH1)  -wlf wave_file1.wlf -l test1.log  -sv_seed random  work.top +UVM_TESTNAME=test1
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov1
	
run_test2_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH2)  -wlf wave_file2.wlf -l test2.log  -sv_seed random  work.top +UVM_TESTNAME=test2
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov2
	
run_test3_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH3)  -wlf wave_file3.wlf -l test3.log  -sv_seed random  work.top +UVM_TESTNAME=test3
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov3

run_test4_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH4)  -wlf wave_file4.wlf -l test4.log  -sv_seed random  work.top +UVM_TESTNAME=test4
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov4

run_test5_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH5)  -wlf wave_file5.wlf -l test5.log  -sv_seed random  work.top +UVM_TESTNAME=test5
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov5
	
run_test6_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH6)  -wlf wave_file6.wlf -l test6.log  -sv_seed random  work.top +UVM_TESTNAME=test6
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov6

run_test7_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH7)  -wlf wave_file7.wlf -l test7.log  -sv_seed random  work.top +UVM_TESTNAME=test7
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov7
	
 
 
###########################################

##   VIRTUAL TEST CASES COMMANDS

########################################

run_vtest_idle_Questa: sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH_IDLE)  -wlf wave_file_idle.wlf -l test_idle.log  -sv_seed random  work.top +UVM_TESTNAME=v_idle_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov_idle
	
run_vtest_busy_Questa: sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH_BUSY)  -wlf wave_file_busy.wlf -l test_busy.log  -sv_seed random  work.top +UVM_TESTNAME=v_busy_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov_busy
	
run_vtest0_Questa: sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH0)  -wlf wave_file0.wlf -l test0.log  -sv_seed random  work.top +UVM_TESTNAME=v0_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov0
	

run_vtest1_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH1)  -wlf wave_file1.wlf -l test1.log  -sv_seed random  work.top +UVM_TESTNAME=v1_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov1
	
run_vtest2_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH2)  -wlf wave_file2.wlf -l test2.log  -sv_seed random  work.top +UVM_TESTNAME=v2_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov2
	
run_vtest3_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH3)  -wlf wave_file3.wlf -l test3.log  -sv_seed random  work.top +UVM_TESTNAME=v3_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov3

run_vtest4_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH4)  -wlf wave_file4.wlf -l test4.log  -sv_seed random  work.top +UVM_TESTNAME=v4_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov4

run_vtest5_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH5)  -wlf wave_file5.wlf -l test5.log  -sv_seed random  work.top +UVM_TESTNAME=v5_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov5
	
run_vtest6_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH6)  -wlf wave_file6.wlf -l test6.log  -sv_seed random  work.top +UVM_TESTNAME=v6_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov6

run_vtest7_Questa:sv_cmp
	vsim -cvgperinstance $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH7)  -wlf wave_file7.wlf -l test7.log  -sv_seed random  work.top +UVM_TESTNAME=v7_test
	vcover report  -cvg  -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov7
	
vregress_Questa: clean_Questa run_test_Questa run_vtest_idle run_vtest_busy run_vtest0_Questa run_vtest1_Questa run_vtest2_Questa run_vtest3_Questa run_vtest4_Questa run_vtest5_Questa run_vtest6_Questa run_vtest7_Questa report_Questa 


#################################################
###################################################



view_wave0_Questa:
	vsim -view wave_file0.wlf
	
view_wave1_Questa:
	vsim -view wave_file1.wlf
	
view_wave2_Questa:
	vsim -view wave_file2.wlf
	
view_wave3_Questa:
	vsim -view wave_file3.wlf
	
view_wave4_Questa:
	vsim -view wave_file4.wlf
 
view_wave5_Questa:
	vsim -view wave_file5.wlf
 
 view_wave6_Questa:
	vsim -view wave_file6.wlf
 
 view_wave7_Questa:
	vsim -view wave_file7.wlf

report_Questa:
	vcover merge mem_cov mem_cov0 mem_cov1 mem_cov2 mem_cov3 mem_cov4 mem_cov5 mem_cov6 mem_cov7  mem_cov_idle mem_cov_busy
	vcover report -cvg -details -nocompactcrossbins -codeAll -assert -directive -html mem_cov

regress_Questa: clean_Questa run_test_Questa run_test_idle run_test_busy run_test0_Questa run_test1_Questa run_test2_Questa run_test3_Questa run_test4_Questa run_test5_Questa run_test6_Questa run_test7_Questa report_Questa 

cov_Questa:
	firefox covhtmlreport/index.html&
	
clean_Questa:
	rm -rf transcript* *log* fcover* covhtml* mem_cov* *.wlf modelsim.ini work
	clear

# ----------------------------- End of Definitions for Mentor's Questa Specific Targets -------------------------------#


# ----------------------------- Start of Definitions for Synopsys's VCS Specific Targets -------------------------------#

sv_cmp_VCS:
	vcs -l vcs.log -timescale=1ns/1ps -sverilog -ntb_opts uvm -debug_access+all -full64 -kdb  -lca -P $(FSDB_PATH)/novas.tab $(FSDB_PATH)/pli.a $(RTL) $(INC) $(SVTB2) $(SVTB1)
		      
run_test_VCS:	clean  sv_cmp_VCS
	./simv -a vcs.log +fsdbfile+wave.fsdb -cm_dir ./mem_cov +ntb_random_seed_automatic +UVM_TESTNAME=base_test 
	urg -dir mem_cov.vdb -format both -report urgReport

run_test0_VCS:	clean  sv_cmp_VCS
	./simv -a vcs.log +fsdbfile+wave0.fsdb -cm_dir ./mem_cov0 +ntb_random_seed_automatic +UVM_TESTNAME=test0 
	urg -dir mem_cov0.vdb -format both -report urgReport0

run_test1_VCS:	clean  sv_cmp_VCS
	./simv -a vcs.log +fsdbfile+wave1.fsdb -cm_dir ./mem_cov1 +ntb_random_seed_automatic +UVM_TESTNAME=test1 
	urg -dir mem_cov1.vdb -format both -report urgReport1
	
run_test2_VCS:	clean  sv_cmp_VCS
	./simv -a vcs.log +fsdbfile+wave2.fsdb -cm_dir ./mem_cov2 +ntb_random_seed_automatic +UVM_TESTNAME=test2 
	urg -dir mem_cov2.vdb -format both -report urgReport2
	
run_test3_VCS:	clean  sv_cmp_VCS
	./simv -a vcs.log +fsdbfile+wave3.fsdb -cm_dir ./mem_cov3 +ntb_random_seed_automatic +UVM_TESTNAME=test3 
	urg -dir mem_cov3.vdb -format both -report urgReport3

run_test4_VCS:	
	./simv -a vcs.log +fsdbfile+wave4.fsdb -cm_dir ./mem_cov4 +ntb_random_seed_automatic +UVM_TESTNAME=test4 
	urg -dir mem_cov4.vdb -format both -report urgReport4

run_test5_VCS:	
	./simv -a vcs.log +fsdbfile+wave5.fsdb -cm_dir ./mem_cov5 +ntb_random_seed_automatic +UVM_TESTNAME=test5 
	urg -dir mem_cov5.vdb -format both -report urgReport5

run_test6_VCS:	
	./simv -a vcs.log +fsdbfile+wave6.fsdb -cm_dir ./mem_cov6 +ntb_random_seed_automatic +UVM_TESTNAME=test6 
	urg -dir mem_cov6.vdb -format both -report urgReport6

run_test7_VCS:	
	./simv -a vcs.log +fsdbfile+wave7.fsdb -cm_dir ./mem_cov7 +ntb_random_seed_automatic +UVM_TESTNAME=test7 
	urg -dir mem_cov7.vdb -format both -report urgReport7

view_wave_VCS: 
	verdi -ssf wave.fsdb
 
view_wave0_VCS: 
	verdi -ssf wave0.fsdb

view_wave1_VCS: 
	verdi -ssf wave1.fsdb
	
view_wave2_VCS: 
	verdi -ssf wave2.fsdb

view_wave3_VCS: 
	verdi -ssf wave3.fsdb

view_wave4_VCS: 
	verdi -ssf wave4.fsdb	
  
view_wave5_VCS: 
	verdi -ssf wave5.fsdb
	
view_wave6_VCS: 
	verdi -ssf wave6.fsdb

view_wave7_VCS: 
	verdi -ssf wave7.fsdb

		
	
report_VCS:
	urg -dir mem_cov0.vdb mem_cov0.vdf mem_cov1.vdb mem_cov2.vdb mem_cov3.vdb mem_cov4.vdb mem_cov5.vdb mem_cov6.vdb mem_cov7.vdb -dbname merged_dir/merged_test -format both -report urgReport

regress_VCS: clean_VCS sv_cmp_VCS run_test_VCS run_test0_VCS run_test1_VCS run_test2_VCS run_test3_VCS run_test4_VCS run_test5_VCS run_test6_VCS run_test7_VCS report_VCS

cov_VCS:
	verdi -cov -covdir merged_dir.vdb

clean_VCS:
	rm -rf simv* csrc* *.tmp *.vpd *.vdb *.key *.log *hdrs.h urgReport* *.fsdb novas* verdi*
	clear

# ----------------------------- END of Definitions for Synopsys's VCS Specific Targets -------------------------------#

